### ISSUE TITLE
Editormodule AddJammer with only sync'ed trigger fails to spawn dataterminal and set it as a jammer

### ISSUE THREAD

**Issue by ItsGiantCookie** [Crowdedlight/Crows-Electronic-Warfare#106]
Due to missing Docs, I'm unsure how to toggle a Jammer with a Trigger, since the Add Jammer Module appears to no place one if the trigger is activated.

**Comment by b-mayr-1984** [comment]
> Due to missing Docs, I'm unsure how to toggle a Jammer with a Trigger, since the Add Jammer Module appears to no place one if the trigger is activated 

@ItsGiantCookie have you found this?
https://crowdedlight.github.io/Crows-Electronic-Warfare/jamming/script.html

**Comment by Crowdedlight** [comment]
Seems like there is a bug. So usually if you got nothing sync'ed to the module, it will spawn an dataterminal and set that as the jammer. However if you have something sync'ed to it, it will make that the jammer instead of spawning a dataterminal. 

However I seem to not take into account if what is sync'ed is a trigger or object. So if anything, like a trigger, is sync'ed, then it won't spawn a dataterminal and thus the jammer can not activate as there is no object to apply it to. 

I will look at fixing it. 

For now, you can manually put down an dataterminal and sync that together with the trigger. When the trigger is activated the dataterminal will open and activate with the jammer settings set in the module. 

![billede](https://github.com/user-attachments/assets/97b30522-f667-4f09-9853-f05c36c0ea13)

**Comment by ItsGiantCookie** [comment]
Hey, sorry to have caused you this trouble, I found the Issue, it was a really simple mistake on my side, a missing apostrophe. Since the trigger checks the missionNamespace and adds the jammer based on that, the error was not caught until I debuged the trigger.
Another question though, how can I disable/remove a Jammer with a script without destroying the structure?

**Comment by b-mayr-1984** [comment]
> Another question though, how can I disable/remove a Jammer with a script without destroying the structure?

See the screenshot at the very bottom of this wiki page.
https://crowdedlight.github.io/Crows-Electronic-Warfare/jamming/general.html

**Comment by ItsGiantCookie** [comment]
I want to do that without Zeus involvement

**Comment by Crowdedlight** [comment]
> I want to do that without Zeus involvement

You should be able to toggle between turned on or off by calling this where ``_jammer`` is the object having the jammer. 

```sqf
[null, null, null, [netId _jammer]] call crowsew_main_fnc_actionJamToggle;
```

**Comment by ItsGiantCookie** [comment]
Thanks for the assist, I'll be closing the Issue for now
