### ISSUE TITLE
Issues with ugv jamming

### ISSUE THREAD

**Issue by Willowoccults** [Crowdedlight/Crows-Electronic-Warfare#37]
if you give a spectrum device to a AI with the jamming antenna and no players have one it will be stuck at around the 200s but when you give a player the device open it and then go back to remote controlling a AI you will have the correct frequency.

**Comment by Willowoccults** [comment]
https://youtu.be/WbFBVZEoYoQ here is a video of what is happening and how i figured out how to fix it.

**Comment by Crowdedlight** [comment]
Thanks for the report and video. I think I know what happens. For performance reasons, the signal calculations don't happen unless the player got a spectrum device. And the way it handles "remote control" just changes the unit it uses to calculate direction and signal, but I don't believe it checks if the calculations are running, and otherwise starts them. 

I'll look into it. It will likely take some weeks as I have very little free-time atm.

**Comment by Crowdedlight** [comment]
Fixed on develop. waiting release

**Comment by Crowdedlight** [comment]
update Released
